### ISSUE TITLE
any readme and dataset?

### ISSUE THREAD

**Issue by SeekPoint** [cabadsanchez/relation_classification#1]

**Comment by cabadsanchez** [comment]
Hi @loveJasmine, 

You can find the dataset used in [data/semeval2010_task8](https://github.com/cabadsanchez/relation_classification/tree/master/data/semeval2010_task8).

As for README, I don't plan to write one because this repo was a quick development for my Master's Thesis. You can check the [slides](https://slides.com/cabadsanchez/deck) I used (in spanish), though.
